
# General Workflow settings
jubeversion: 2.3.0
outpath: output

# Default benchmark choices
default:
  simulator: nest-simulator
  model: hpc_benchmark
  benchmark: thread_scaling
  machine: laptop

