parameterset:
    name: user_config
    parameter:
      - {name: account, type: string, _: ACCOUNT} # slurm account name for job submission
      - {name: email_address, type: string, _: EMAIL_ADDRESS} # (optional) email address to which slurm sends START, END, FAIL emails for job progress info
      - {name: partition, type: string, _: PARTITION} # (optional, required on some machines) cluster partition, takes system default if left empty 
