channels:
  - defaults
dependencies:
  - cmake=3.14
  - cython>=0.29.15
  - matplotlib>=3.1.3
  - numpy>=1.18.1
  - gcc_linux-64
  - gxx_linux-64
  #- binutils_linux-64
  - gsl=2.4
  - libtool
  - pip>=20
  - python=3.8

